version: '3'
name: base-services-config
services:
  nginx-server:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    network_mode: bridge
    volumes:
      - type: bind
        source: ./nginx/variables/
        target: /etc/nginx/templates/
      - type: bind
        source: ./nginx/servers
        target: /etc/nginx/conf.d/
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf/:/etc/nginx/ssl/
    environment:
      CUSTOM_DOMAIN_NAME: ${CUSTOM_DOMAIN_NAME}
      DEFAULT_SERVER_NAMES: ${DEFAULT_SERVER_NAMES}
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot/