version: '3'
name: base-services-config
services:
  nginx-server:
    image: nginx:latest
    ports:
      - "${PORT}:${PORT}"
    network_mode: bridge
    volumes:
      - type: bind
        source: ./nginx/variables/
        target: /etc/nginx/templates/
      - type: bind
        source: ./nginx/servers
        target: /etc/nginx/conf.d/
    environment:
      CUSTOM_DOMAIN_NAME: ${CUSTOM_DOMAIN_NAME}
      DEFAULT_SERVER_NAMES: ${DEFAULT_SERVER_NAMES}
      LOCATION_PORT: ${LOCATION_PORT}
      PROTOCOL: ${PROTOCOL}