version: '3'

services:
  nginx:
    build: .
    ports:
      - "4000:4000"
    network_mode: bridge
    volumes:
      - ./nginx/template-variables:/etc/nginx/templates/10-variables.conf.template:ro
    environment:
      CUSTOM_DOMAIN_NAME: ${CUSTOM_DOMAIN_NAME}