name: ci dev

on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      STAGE: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy docker-compose and nginx config files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key:  ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          target: ./nginx
          rm: true
          source: "docker-compose.yml,nginx/*"
      -
        name: Execute startup commands and set enviroment variables in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key:  ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          script: |
            export CUSTOM_DOMAIN_NAME=${{ vars.CUSTOM_DOMAIN_NAME }}
            export DEFAULT_SERVER_NAMES='${{ vars.DEFAULT_SERVER_NAMES }}'
            export LOCATION_PORT=${{ vars.LOCATION_PORT }}
            export PROTOCOL=${{ vars.PROTOCOL }}
            export PORT=${{ vars.PORT }}
            echo "$CUSTOM_DOMAIN_NAME"
            echo "$LOCATION_PORT"
            echo "$PROTOCOL"
            cd nginx
            docker-compose down
            docker-compose build
            docker-compose up -d